export const CREATE_BILLBOARD_SUCCESS = "CREATE_BILLBOARD_SUCCESS";
export const CREATE_BILLBOARD_FAIL = "CREATE_BILLBOARD_FAIL";
export const CREATE_BILLBOARD_LOADING = "CREATE_BILLBOARD_LOADING";

export const ADD_IMAGES_TO_BILLBOARD_SUCCESS =
  "ADD_IMAGES_TO_BILLBOARD_SUCCESS";
export const ADD_IMAGES_TO_BILLBOARD_FAIL = "ADD_IMAGES_TO_BILLBOARD_FAIL";
export const ADD_IMAGES_TO_BILLBOARD_LOADING =
  "ADD_IMAGES_TO_BILLBOARD_LOADING";

export const GET_BILLBOARD_SUCCESS = "GET_BILLBOARD_SUCCESS";
export const GET_BILLBOARD_FAIL = "GET_BILLBOARD_FAIL";
export const GET_BILLBOARD_LOADING = "GET_BILLBOARD_LOADING";

export const SELECT_BILLBOARD_LOADING = "SELECT_BILLBOARD_LOADING";
export const SELECT_BILLBOARD_SUCCESS = "SELECT_BILLBOARD_SUCCESS";
export const SELECT_BILLBOARD_FAIL = "SELECT_BILLBOARD_FAIL";

export const GET_HOME_BILLBOARD_FAIL = "GET_HOME_BILLBOARD_FAIL";
export const GET_HOME_BILLBOARD_SUCCESS = "GET_HOME_BILLBOARD_SUCCESS";
export const GET_HOME_BILLBOARD_LOADING = "GET_HOME_BILLBOARD_LOADING";
